\ProvidesPackage{datamining}
\LoadClass[a4paper,12pt]{report}

\setlength{\oddsidemargin}{-0.04cm}
\setlength{\evensidemargin}{-0.04cm}
\setlength{\textwidth}{16cm}
\setlength{\topmargin}{-0.54cm}
\setlength{\headheight}{0.8cm}
\setlength{\headsep}{1.0cm}
\setlength{\textheight}{22.5cm}
\setlength{\footskip}{1.45cm}

\RequirePackage{fontspec}
\setmainfont{Inter-Regular.otf}[Path=./fonts/,
BoldFont=Inter-Bold.otf,
ItalicFont=Inter-Italic.otf,
BoldItalicFont=Inter-BoldItalic.otf,
Mapping=tex-text]
\setsansfont{Inter-Regular.otf}[Path=./fonts/,
BoldFont=Inter-Bold.otf,
ItalicFont=Inter-Italic.otf,
BoldItalicFont=Inter-BoldItalic.otf,
Mapping=tex-text]